//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionarios
    {
        public string EmailUtilizador { get; set; }
        public int FarmaciaId { get; set; }
        public string Categoria { get; set; }
    
        public virtual Farmacias Farmacias { get; set; }
        public virtual Utilizadores Utilizadores { get; set; }
    }
}
