//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venda()
        {
            this.VendaProduto = new HashSet<VendaProduto>();
        }
    
        public int Id { get; set; }
        public System.DateTime DataVenda { get; set; }
        public string Tipo { get; set; }
        public decimal ValorTotal { get; set; }
        public string Cliente { get; set; }
        public Nullable<int> FarmaciaId { get; set; }
    
        public virtual Farmacia Farmacia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendaProduto> VendaProduto { get; set; }
    }
}
